### ISSUE TITLE
Improve error tracking

### ISSUE THREAD

**Issue by jnraine** [integrations/jira#231]
When an exception occurs, it is sent to Sentry. The error appears in Sentry but it looks strange. For example, the stacktrace doesn't include any lines from the codebase and the breadcrumbs appear to include logs from different requests.

### Unhelpful stacktrace

```
Error: Request failed with status code 404
  File "/app/node_modules/axios/lib/core/createError.js", line 16, col 15, in createError
    var error = new Error(message);
  File "/app/node_modules/axios/lib/core/settle.js", line 18, col 12, in settle
    reject(createError(
  File "/app/node_modules/axios/lib/adapters/http.js", line 201, col 11, in IncomingMessage.handleStreamEnd
    settle(resolve, reject, response);
  File "events.js", line 208, col 15, in IncomingMessage.emit
  File "domain.js", line 476, col 20, in IncomingMessage.EventEmitter.emit
  File "/app/node_modules/newrelic/lib/transaction/tracer/index.js", line 181, col 22, in IncomingMessage.wrapped
    return handler.apply(this, arguments)
  File "/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js", line 205, col 24, in IncomingMessage.wrappedResponseEmit
    return boundEmit.apply(this, arguments)
  File "_stream_readable.js", line 1168, col 12, in endReadableNT
  File "/app/node_modules/newrelic/lib/shim/shim.js", line 1396, col 20, in Shim.applySegment
    return fnApply.call(func, context, args)
  File "/app/node_modules/newrelic/lib/shim/shim.js", line 2020, col 17, in wrapper
    return shim.applySegment(fn, segment, full, this, arguments)
  File "internal/process/task_queues.js", line 77, col 11, in processTicksAndRejections
```

If you have access to production Sentry, [see it here](https://sentry.io/organizations/github-integrations/issues/1144567048).

### Breadcrumbs

![image](https://user-images.githubusercontent.com/300976/62789537-f8d68f00-ba7d-11e9-8bcd-4820489daffa.png)

### Objective

- [x] Isolate breadcrumbs between requests and jobs
- [ ] ~~Improve stacktrace (I'm not entirely sure why it excludes our code)~~ Seems like the nature of unhandled promises. Will work on it bit-by-bit.
- [x] Release tracking w/ commits
- [x] Track user using `installationId`, not IP?

**Comment by jnraine** [comment]
Improvements made in the following PRs: https://github.com/integrations/jira/pull/236,https://github.com/integrations/jira/pull/238, https://github.com/integrations/jira/pull/239, https://github.com/integrations/jira/pull/241, https://github.com/integrations/jira/pull/242, https://github.com/integrations/jira/pull/242, https://github.com/integrations/jira/pull/244

Things are looking much better now. ✌️
